<a href="https://colab.research.google.com/github/MoisesBC137/analise-vendas-lookerstudio/blob/main/fun%C3%A7oes_basicas2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import pandas as pd
import numpy as np # Necessário para o exemplo de criação de dados

# 1. FUNÇÃO PRINCIPAL: Criação de um DataFrame
dados = {
    'Nome': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Idade': [25, 30, 35, 22, 28],
    'Salario': [50000, 60000, 75000, 40000, 55000],
    'Cidade': ['SP', 'RJ', 'MG', 'SP', 'RJ']
}
df = pd.DataFrame(dados)

print("--- DataFrame Inicial ---")
print(df)
print("\n" + "-"*30 + "\n")

# 2. SELEÇÃO E FILTRAGEM (iloc/loc)
# Seleciona todas as linhas e a coluna 'Salario' (usando o nome da coluna)
salarios = df['Salario']
print("2. Coluna 'Salario':")
print(salarios)
print("\n")

# Filtragem de linhas: Pessoas com mais de 28 anos
df_filtrado = df[df['Idade'] > 28]
print("2. Pessoas com Idade > 28:")
print(df_filtrado)
print("\n")

# 3. AGRUPAMENTO E AGREGAÇÃO (groupby)
# Calcula a média do salário por cidade
media_por_cidade = df.groupby('Cidade')['Salario'].mean()
print("3. Média Salarial por Cidade:")
print(media_por_cidade)
print("\n")

# 4. TRATAMENTO DE VALORES NULOS (fillna/dropna)
# Cria um valor nulo proposital para demonstração
df.loc[0, 'Salario'] = np.nan

# Preenche o valor nulo com a média da coluna 'Salario'
df['Salario_Preenchido'] = df['Salario'].fillna(df['Salario'].mean())
print("4. DataFrame com Salário Preenchido (NaN na 1ª linha):")
print(df[['Salario', 'Salario_Preenchido']])

--- DataFrame Inicial ---
      Nome  Idade  Salario Cidade
0    Alice     25    50000     SP
1      Bob     30    60000     RJ
2  Charlie     35    75000     MG
3    David     22    40000     SP
4      Eva     28    55000     RJ

------------------------------

2. Coluna 'Salario':
0    50000
1    60000
2    75000
3    40000
4    55000
Name: Salario, dtype: int64


2. Pessoas com Idade > 28:
      Nome  Idade  Salario Cidade
1      Bob     30    60000     RJ
2  Charlie     35    75000     MG


3. Média Salarial por Cidade:
Cidade
MG    75000.0
RJ    57500.0
SP    45000.0
Name: Salario, dtype: float64


4. DataFrame com Salário Preenchido (NaN na 1ª linha):
   Salario  Salario_Preenchido
0      NaN             57500.0
1  60000.0             60000.0
2  75000.0             75000.0
3  40000.0             40000.0
4  55000.0             55000.0


In [21]:
import numpy as np

# 1. FUNÇÃO PRINCIPAL: Criação de Arrays (ndarrays)
# Array unidimensional (vetor)
vetor = np.array([10, 20, 30, 40, 50])

# Array bidimensional (matriz)
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("--- Arrays NumPy ---")
print("1. Vetor:\n", vetor)
print("1. Matriz:\n", matriz)
print("\n" + "-"*30 + "\n")

# 2. OPERAÇÕES VETORIZADAS
# Aplica uma operação a todos os elementos do array de uma vez (ex: soma 5)
vetor_soma = vetor + 5
print("2. Vetor + 5:\n", vetor_soma)
print("\n")

# 3. OPERAÇÕES ESTATÍSTICAS
# Média, desvio padrão e máximo
media = np.mean(vetor)
desvio = np.std(vetor)
maximo = np.max(vetor)
print(f"3. Estatísticas do Vetor: Média={media:.2f}, Desvio={desvio:.2f}, Máximo={maximo}")
print("\n")

# 4. INDEXAÇÃO E SLICING
# Seleciona a segunda linha (índice 1)
segunda_linha = matriz[1, :]
print("4. Segunda Linha da Matriz (índice 1):\n", segunda_linha)
print("\n")

# 5. REMODELAGEM (Reshape)
# Transforma o array unidimensional de volta para 5x1 (útil para modelos)
vetor_reshape = vetor.reshape((5, 1))
print("5. Vetor Remodelado (5 linhas, 1 coluna):\n", vetor_reshape)

--- Arrays NumPy ---
1. Vetor:
 [10 20 30 40 50]
1. Matriz:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

------------------------------

2. Vetor + 5:
 [15 25 35 45 55]


3. Estatísticas do Vetor: Média=30.00, Desvio=14.14, Máximo=50


4. Segunda Linha da Matriz (índice 1):
 [4 5 6]


5. Vetor Remodelado (5 linhas, 1 coluna):
 [[10]
 [20]
 [30]
 [40]
 [50]]


# Nova seção

In [22]:
import numpy as np  # Importa o NumPy para cálculos numéricos e matemáticos
import pandas as pd  # Importa o Pandas para usar as funções estatísticas em tabelas

# 1. PREPARANDO OS DADOS DE EXEMPLO
# Criando uma lista com o faturamento diário de uma loja ao longo de 7 dias
faturamento_diario = [2200, 1800, 2500, 2200, 9500, 1900, 2100]
df_estatistica = pd.DataFrame(faturamento_diario, columns=["Faturamento"])

# 2. CÁLCULO DE TENDÊNCIA CENTRAL
# Calcula a Média: Soma tudo e divide pela quantidade (é afetada por valores muito altos)
media_faturamento = df_estatistica["Faturamento"].mean()

# Calcula a Mediana: Organiza em ordem crescente e pega o valor exatamente do meio
mediana_faturamento = df_estatistica["Faturamento"].median()

# 3. CÁLCULO DE DISPERSÃO (VARIABILIDADE)
# Calcula o Desvio Padrão: Mostra o quanto os valores variam em relação à média
desvio_padrao = df_estatistica["Faturamento"].std()

# 4. ANÁLISE DE CORRELAÇÃO
# Criando uma segunda variável (Investimento em Anúncios) para cruzar dados
df_estatistica["Investimento_Anuncios"] = [200, 150, 260, 210, 900, 180, 220]

# Calcula a Matriz de Correlação entre Faturamento e Investimento em Anúncios
# Próximo de 1 = Forte relação positiva | Próximo de 0 = Sem relação
matriz_correlacao = df_estatistica.corr()

# EXIBIÇÃO DOS RESULTADOS E ANOTAÇÕES
print(f"Média de Faturamento: R$ {media_faturamento:.2f}")  # Indica o valor médio geral
print(f"Mediana de Faturamento: R$ {mediana_faturamento:.2f}")  # Ignora o valor discrepante (9500)
print(f"Desvio Padrão: R$ {desvio_padrao:.2f}")  # Indica alta variação por conta do pico de 9500
print("\n--- Matriz de Correlação ---")
print(matriz_correlacao)  # Mostra se investir em anúncios aumenta o faturamento


Média de Faturamento: R$ 3171.43
Mediana de Faturamento: R$ 2200.00
Desvio Padrão: R$ 2799.83

--- Matriz de Correlação ---
                       Faturamento  Investimento_Anuncios
Faturamento               1.000000               0.998304
Investimento_Anuncios     0.998304               1.000000
